# Generated by Django 5.1.1 on 2024-10-14 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Eshop_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='address_number',
            field=models.CharField(default='0', max_length=10, verbose_name='Číslo popisné'),
        ),
        migrations.AddField(
            model_name='user',
            name='first_name',
            field=models.CharField(default='Nepřiřazeno', max_length=100, verbose_name='Jméno'),
        ),
        migrations.AddField(
            model_name='user',
            name='last_name',
            field=models.CharField(default='Nepřiřazeno', max_length=100, verbose_name='Příjmení'),
        ),
        migrations.AlterField(
            model_name='user',
            name='address_city',
            field=models.CharField(default='Nepřiřazeno', max_length=100),
        ),
        migrations.AlterField(
            model_name='user',
            name='address_country',
            field=models.CharField(default='Nepřiřazeno', max_length=100),
        ),
        migrations.AlterField(
            model_name='user',
            name='address_street',
            field=models.CharField(default='Nepřiřazeno', max_length=100),
        ),
        migrations.AlterField(
            model_name='user',
            name='address_zip',
            field=models.CharField(default='00000', max_length=5),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(default='noemail@example.com', max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(default='defaultpassword', max_length=100),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(default='Nepřiřazeno', max_length=100, unique=True),
        ),
    ]
