# Generated by Django 5.1.1 on 2024-10-14 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Eshop_app', '0002_user_address_number_user_first_name_user_last_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='address_city',
            field=models.CharField(default='Vyplňte prosím', max_length=100),
        ),
        migrations.AlterField(
            model_name='user',
            name='address_country',
            field=models.CharField(default='Vyplňte prosím', max_length=100),
        ),
        migrations.AlterField(
            model_name='user',
            name='address_number',
            field=models.CharField(default='Vyplňte prosím', max_length=10, verbose_name='Číslo popisné'),
        ),
        migrations.AlterField(
            model_name='user',
            name='address_street',
            field=models.CharField(default='Vyplňte prosím', max_length=100),
        ),
        migrations.AlterField(
            model_name='user',
            name='address_zip',
            field=models.CharField(default='Vyplňte prosím', max_length=5),
        ),
        migrations.AlterField(
            model_name='user',
            name='first_name',
            field=models.CharField(default='Vyplňte prosím', max_length=100),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_name',
            field=models.CharField(default='Vyplňte prosím', max_length=100, verbose_name='Příjmení'),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(default='Vyplňte prosím', max_length=100, unique=True),
        ),
    ]
