# Generated by Django 4.1 on 2024-09-30 17:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Eshop_app', '0002_user_category_parent_category_product_description_and_more'),
        ('Eshop_app', '0006_alter_product_image'),
    ]

    operations = [
    ]
